/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    theme: {
        extend: {
            fontFamily: {
                heading: ['Sora', 'sans-serif'],
                body: ['Plus Jakarta Sans', 'sans-serif'],
                mono: ['IBM Plex Mono', 'monospace'],
                pixel: ['Pixelify Sans', 'sans-serif'],
            },
            colors: {
                ink: '#0A0A0C',
                ink2: '#0A0A0C',
                plum: '#0A0A0C',
                plum2: '#15141E',
                plumborder: '#E9D5FF',
                violet: '#E9D5FF',
                violet2: '#8B5CF6',
                lavender: '#C4B5FD',
                lavender2: '#A78BFA',
                coral: '#F97316',
                coral2: '#FB923C',
                mint: '#34D399',
                gold: '#FBBF24',
                rose: '#F43F5E',
                charcoal: '#0A0A0C',
                slate: '#15141E',
                'slate-light': '#2E2456',
                teal: '#8B5CF6',
                'teal-light': '#A78BFA',
                amber: '#FBBF24',
                paper: '#0A0A0C',
                moss: '#34D399',
                mustard: '#FBBF24',
                rust: '#F43F5E',
                warm: '#E9D5FF',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
                popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
                primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
                secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
                muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
                accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
                destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 4px)',
                sm: 'calc(var(--radius) - 8px)',
            },
            keyframes: {
                'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
                'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
