/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    theme: {
        extend: {
            fontFamily: {
                heading: ['Sora', 'sans-serif'],
                body: ['Plus Jakarta Sans', 'sans-serif'],
                mono: ['IBM Plex Mono', 'monospace'],
                pixel: ['Pixelify Sans', 'sans-serif'],
            },
            colors: {
                ink: '#000000',
                ink2: '#000000',
                plum: '#000000',
                plum2: '#24201A',
                plumborder: '#92400E',
                violet: '#F5C542',
                violet2: '#F5C542',
                lavender: '#FFF8E1',
                lavender2: '#FFF8E1',
                coral: '#F5C542',
                coral2: '#F5C542',
                mint: '#F59E0B',
                gold: '#F5C542',
                rose: '#F59E0B',
                charcoal: '#000000',
                slate: '#24201A',
                'slate-light': '#92400E',
                teal: '#F5C542',
                'teal-light': '#92400E',
                amber: '#F5C542',
                paper: '#000000',
                moss: '#F59E0B',
                mustard: '#FFD84D',
                rust: '#F59E0B',
                warm: '#FFF8E1',
                background: '#000000',
                foreground: '#FFF8E1',
                card: { DEFAULT: '#24201A', foreground: '#FFF8E1' },
                popover: { DEFAULT: '#24201A', foreground: '#FFF8E1' },
                primary: { DEFAULT: '#F5C542', foreground: '#000000' },
                secondary: { DEFAULT: '#F59E0B', foreground: '#000000' },
                muted: { DEFAULT: '#24201A', foreground: '#FFF8E1' },
                accent: { DEFAULT: '#FFD84D', foreground: '#000000' },
                destructive: { DEFAULT: '#92400E', foreground: '#FFF8E1' },
                border: '#92400E',
                input: '#92400E',
                ring: '#92400E',
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 4px)',
                sm: 'calc(var(--radius) - 8px)',
            },
            keyframes: {
                'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
                'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
                'marquee': { '0%': { transform: 'translateX(0%)' }, '100%': { transform: 'translateX(-50%)' } },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
                'marquee': 'marquee 25s linear infinite',
            },
        },
    },
    plugins: [
        require("tailwindcss-animate"),
        require("@tailwindcss/typography")
    ],
};
