/**
 * Maps Minecraft version strings to Resource Pack format requirements.
 * Data sourced from https://minecraft.wiki/w/Pack_format
 * 
 * Update this table as new Minecraft versions are released.
 */
const RESOURCE_PACK_FORMATS = [
  // Future/Newest format style (Minecraft 1.21.9+)
  // { minVersion: "1.21.9", maxVersion: "1.21.9", type: "range", min_format: 50, max_format: 50 },
  
  // Current format style
  { minVersion: "1.21.4", maxVersion: "1.21.5", type: "both", pack_format: 46, min_supported: 46, max_supported: 46 },
  { minVersion: "1.21.2", maxVersion: "1.21.3", type: "both", pack_format: 42, min_supported: 42, max_supported: 42 },
  { minVersion: "1.21", maxVersion: "1.21.1", type: "both", pack_format: 34, min_supported: 34, max_supported: 34 },
  { minVersion: "1.20.5", maxVersion: "1.20.6", type: "both", pack_format: 32, min_supported: 32, max_supported: 32 },
  { minVersion: "1.20.3", maxVersion: "1.20.4", type: "both", pack_format: 22, min_supported: 22, max_supported: 22 },
  { minVersion: "1.20.2", maxVersion: "1.20.2", type: "both", pack_format: 18, min_supported: 18, max_supported: 18 },
  
  // Legacy format style (Pre 1.20.2)
  { minVersion: "1.20", maxVersion: "1.20.1", type: "legacy", pack_format: 15 },
  { minVersion: "1.19.4", maxVersion: "1.19.4", type: "legacy", pack_format: 13 },
  { minVersion: "1.19.3", maxVersion: "1.19.3", type: "legacy", pack_format: 12 },
  { minVersion: "1.19", maxVersion: "1.19.2", type: "legacy", pack_format: 9 },
  { minVersion: "1.18", maxVersion: "1.18.2", type: "legacy", pack_format: 8 },
  { minVersion: "1.17", maxVersion: "1.17.1", type: "legacy", pack_format: 7 },
  { minVersion: "1.16.2", maxVersion: "1.16.5", type: "legacy", pack_format: 6 },
  { minVersion: "1.15", maxVersion: "1.16.1", type: "legacy", pack_format: 5 },
  { minVersion: "1.13", maxVersion: "1.14.4", type: "legacy", pack_format: 4 },
  { minVersion: "1.11", maxVersion: "1.12.2", type: "legacy", pack_format: 3 },
  { minVersion: "1.9", maxVersion: "1.10.2", type: "legacy", pack_format: 2 },
  { minVersion: "1.6.1", maxVersion: "1.8.9", type: "legacy", pack_format: 1 },
];

/**
 * Parses a Minecraft version string (e.g. "1.21.4" or "1.19") into a sortable number
 * 1.21.4 -> 1021004
 * 1.19   -> 1019000
 */
function parseVersion(vStr) {
  const parts = vStr.split('.').map(Number);
  const major = parts[0] || 0;
  const minor = parts[1] || 0;
  const patch = parts[2] || 0;
  return major * 1000000 + minor * 1000 + patch;
}

export function resolvePackFormat(versionString, description = "Generated by Qiveo.dev Minecraft Tools") {
  const targetVer = parseVersion(versionString);
  
  // Find matching format
  let match = null;
  for (const fmt of RESOURCE_PACK_FORMATS) {
    if (targetVer >= parseVersion(fmt.minVersion) && targetVer <= parseVersion(fmt.maxVersion)) {
      match = fmt;
      break;
    }
  }
  
  // Fallback to highest format if not found (newer version)
  if (!match) {
    match = RESOURCE_PACK_FORMATS[0];
  }

  const mcmeta = { pack: { description } };

  if (match.type === 'range') {
    mcmeta.pack.min_format = match.min_format;
    mcmeta.pack.max_format = match.max_format;
  } else if (match.type === 'both') {
    mcmeta.pack.pack_format = match.pack_format;
    mcmeta.pack.supported_formats = [match.min_supported, match.max_supported];
  } else {
    mcmeta.pack.pack_format = match.pack_format;
  }

  return mcmeta;
}
